
GET http://localhost:3016/users?page=1&size=3&search=pa

###
POST http://localhost:3016/signup
Content-Type: application/json

{
    "fullName": "Yahoo User",
    "email": "localhostuser@yahoo.com",
    "telephone": "0786547898",
    "password": "123456"
}

####
POST  http://localhost:3016/signin
Content-Type: application/json

{
    "email": "localhostuser@yahoo.com",
    "password": "123456"
}

###
GET http://localhost:3005/categories

###
POST http://localhost:3005/add-category
Content-Type: application/json

{
     "categoryName":"Wall units"
}

###
POST http://localhost:3005/edit-category
Content-Type: application/json

{
    "categoryId":1,
     "categoryName":"Seaters"
}

###
GET http://localhost:3005/products


###
GET http://localhost:3005/products?page=1&size=3&search=pa
###
post http://localhost:3005/add-product
Content-Type: application/json

{
    "imageUrl":"https://images.unsplash.com/photo-1512212621149-107ffe572d2f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8c29mYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    "productName":"Soft silk 2-seater",
    "price":"35500",
    "description":"This is your ideal resting compaion. An all time chair to suit you.",
    "categoryId": 1
}

###
GET http://localhost:5016/orders

###
POST http://localhost:5016/add-order
Content-Type: application/json

{
    ""
}