
GET http://localhost:3016/users?page=1&size=3&search=pa

###
POST http://localhost:3016/signup
Content-Type: application/json

{
    "fullName": "Yahoo User",
    "email": "laukeymwaura@gmail.com",
    "telephone": "0786547898",
    "password": "123456"
}

####
POST  http://localhost:3016/signin
Content-Type: application/json

{
    "email": "localhostuser@yahoo.com",
    "password": "123456"
}

###
GET http://localhost:3005/categories

###
POST http://localhost:3005/add-category
Content-Type: application/json

{
     "categoryName":"Wall units"
}

###
POST http://localhost:3005/edit-category
Content-Type: application/json

{
    "categoryId":1,
     "categoryName":"Seaters"
}

###
GET http://localhost:3005/products


###
GET http://localhost:3005/products?page=1&size=3&search=pa
###
post http://localhost:3005/edit-product
Content-Type: application/json

{
    "proddId": "3",
    "imageUrl":"https://images.unsplash.com/photo-1540574163026-643ea20ade25?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Y291Y2h8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    "productName":"Leather 3-seater",
    "price":"45500",
    "description":"Leather 3-seater with posh hand rests",
    "categoryId": 2
}

###
GET http://localhost:5016/orders

###
POST http://localhost:5016/add-order?userId=11
Content-Type: application/json

{
        
    "OrderID": 7,
    "OrderDetail": [
        {
            "ProductID": 1,
            "Quantity": 3,
            "UnitPrice": 4350     
        },     
        {            
          "ProductID": 2,
          "Quantity": 3,
          "UnitPrice": 4000
        },
        {            
          "ProductID": 3,
          "Quantity": 2,
          "UnitPrice": 5560
        }
    ],       
}